const { withAppBuildGradle } = require('expo/config-plugins');

// android/ is regenerated by `expo prebuild` and is gitignored, so the release
// signingConfig can't just be hand-edited into build.gradle — it has to be injected
// here, every prebuild, the same way withSmsReceiver.js injects the SMS receiver.
// The actual keystore + passwords live in android-signing/ (gitignored, outside the
// disposable android/ folder) so they survive a `prebuild --clean`.
const SIGNING_BLOCK = `
    def releaseKeystorePropsFile = rootProject.file('../android-signing/release.keystore.properties')
    def releaseKeystoreProps = new Properties()
    if (releaseKeystorePropsFile.exists()) {
        releaseKeystoreProps.load(new FileInputStream(releaseKeystorePropsFile))
    }
`;

function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;

    if (!contents.includes('releaseKeystorePropsFile')) {
      contents = contents.replace(
        /signingConfigs\s*\{/,
        `${SIGNING_BLOCK}\n    signingConfigs {\n        release {\n            if (releaseKeystorePropsFile.exists()) {\n                storeFile rootProject.file("../android-signing/\${releaseKeystoreProps['storeFile']}")\n                storePassword releaseKeystoreProps['storePassword']\n                keyAlias releaseKeystoreProps['keyAlias']\n                keyPassword releaseKeystoreProps['keyPassword']\n            }\n        }`
      );
    }

    // Point the release build type at the release key when it's available, so a
    // machine without android-signing/ (e.g. a clean checkout) still falls back to
    // the debug key instead of failing the build outright. [^}] (not \s*) bridges
    // the "Caution!" comment lines the RN template puts between "release {" and the
    // signingConfig line, without crossing into the debug build type's own block —
    // that block closes with a "}" first, which [^}] can't match through.
    contents = contents.replace(
      /release\s*\{([^}]*?)signingConfig signingConfigs\.debug/,
      `release {$1signingConfig releaseKeystorePropsFile.exists() ? signingConfigs.release : signingConfigs.debug`
    );

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withReleaseSigning;
